### ISSUE TITLE
Spelling of Tyre is in US English Tire

### ISSUE THREAD

**Issue by imellor** [Hyundai-Kia-Connect/kia_uvo#538]
As most of the functionality is based around the European Instance of the Hyundai / Kia servers. I was surprised to see the American spelling of Tire as opposed to English spelling of Tyre..
Is this from the API data or configured locally on the HA Integration?

**Comment by cdnninja** [comment]
While this integration started as EU only it is no longer based on EU. It now has equal integration support for the Canada, and trailing support for both USA brands.   I believe this was added by someone for US then backported to other regions.   I am a primary supporter of this integration and Canadian, we use tire which is probably why I never noticed this before.  

I think ideally we look an localization since I have seen requests for other languages which today we can't fully support.   If I change the tire spelling today I am sure I will get issues the other way too.
