### ISSUE TITLE
Exceeds number of requests

### ISSUE THREAD

**Issue by pwlivewire** [Hyundai-Kia-Connect/kia_uvo#546]
Please check Services, Known Bug / Issues and Troubleshooting over here first: https://github.com/fuatakgun/kia_uvo/blob/master/README.md
**Region and Brand of car**
 EU
 Kia iro
 Kia Sportage
**Version of the integration**
1.7
1.6.10

**Describe the bug**
It was working, but now i get ;
Retrying setup: Config Not Ready: Exceeds number of requests - Exceeds Number of Requests.

**Debug logs if an error occurred**

**To Reproduce**

Occurs constantly

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by cdnninja** [comment]
What is your force frequency set to? As well as your cached frequency?  Those are most likely set too high.  You have maxed out your calls for the day.

**Comment by pwlivewire** [comment]
I've reduced it and suspect your right. Perhaps if learning the call limits you could prevent this threshold from being exceeded?

**Comment by cdnninja** [comment]
Could you help me understand what that would look like?

**Comment by Maximus97** [comment]
Is there any documentation of tested limits? Is Scan Interval and Force Refresh Interval both set to 30 minutes going to cause issues?

**Comment by cdnninja** [comment]
This covers it to some extent.   

https://github.com/Hacksore/bluelinky/wiki/API-Rate-Limits

I don't think having cached and forced at the same interval gives much value.   Idea is to check with the cloud more often for cached since the car naturally checks in for certain reasons. 


As a note 12v battery is used when you force scan.  This can and will drain it.  So use force carefully.

**Comment by pwlivewire** [comment]
hasn't occurred again, think i had the force refresh to aggressive.
